### ISSUE TITLE
Help with Gradual entry to the quiz

### ISSUE THREAD

**Issue by germanvaleroelizondo** [juacas/quizaccess_activatedelayedattempt#10]
Hi,
When testing this great new plugin, I found that the blue question mark that should give Help with gradual entry to the quiz does not work.

![imagen](https://user-images.githubusercontent.com/2671923/86974448-f96b2000-c13b-11ea-87d4-b26ef7779517.png)

**Comment by juacas** [comment]
Now the string 'delayedattemptlock_help' is defined as 'When enabled, on loading the quiz page before the quiz start date the start attempt button is disabled transiently.
A countdown period is started (random up to a time set up by your institution). When the countdown ends the start attempt button is re-enabled and the students can initiate the quiz attempt. ';
