### ISSUE TITLE
Improvement: Please add default text for these 2 strings

### ISSUE THREAD

**Issue by germanvaleroelizondo** [juacas/quizaccess_activatedelayedattempt#11]
Please add a default text for these 2 strings, as it is easier for a user to mofify an existing text than it is to come up with a good one if the user has no previous experience with this plugin:

![imagen](https://user-images.githubusercontent.com/2671923/86974957-d7be6880-c13c-11ea-8b1e-9e70c9956466.png)

**Comment by germanvaleroelizondo** [comment]
Perhaps you can use the text that they use at your University.

_Saludos afectuosos a distancia desde México._

**Comment by juacas** [comment]
These are site-wide settings so it is somehow "intrusive". The default values we use in our University are:

- "notice": A short animation giving advices about how to proceed during the exam.
- "dangerousquiznotice": Empty. This is aimed to emergency situations.

I think it is better to add a detailed description to those settings so the administrator can understand properly how to configure them.
I'm not sure there are a recommended, general way of using that fields.

**Comment by juacas** [comment]
Explanatory descriptions added to admin settings.
