### ISSUE TITLE
JS error Internet explorer

### ISSUE THREAD

**Issue by ed-rom** [juacas/quizaccess_activatedelayedattempt#12]
After installing the plugin I started to have javascript errors in the internet explorer.

SCRIPT1006: Caráter ')' esperado
first.js (418,53)

SCRIPT5022: No define call for core/first http://requirejs.org/docs/errors.html#nodefine
require.min.js (5,927)

When i click in the first error i go:
"define('quizaccess_delayed/timer_flipdown',  ['jquery'], function ($) {
    var strings;
    var quizOpenTime;
    return {
        get_string:...."

I'm using the version Moodle 3.9.1 (Build: 20200713) with Boost and the plugin 1.2.1 (2020051801).

**Comment by juacas** [comment]
Thank you for reporting. Unfortunately I can't support IExplorer for two main reasons:

- I'm not so expert in multi-browser javascript compatibility. Sincerely, I don't know how to fix this problem. I need some help from the community here.
- IExplorer is a deprecated browser.

Maybe someone can help with this.

**Comment by juacas** [comment]
Transpilation of javascript has been added to address this issue.
Now javascript is compatible with the legacy, deprecated Internet Explorer browser.
