### ISSUE TITLE
<noscript></noscript> is filtered out by clean_text() in export_for_template()

### ISSUE THREAD

**Issue by adnbes** [juacas/quizaccess_activatedelayedattempt#31]
mod/quiz/accessrule/delayed/rule.php
![image](https://github.com/juacas/quizaccess_delayed/assets/137163763/64d967b1-347f-428c-9e51-c617fa151fca)

lib/classes/output/notification.php
![image](https://github.com/juacas/quizaccess_delayed/assets/137163763/d36781ca-d051-4a97-a0bd-d9804ff97d66)

_**This quiz requires a browser that supports JavaScript. If you have a Javascript blocker you will need to disable it.**_ =>Will be displayed even if javascript is active.
![image](https://github.com/juacas/quizaccess_delayed/assets/137163763/67383cdf-abcd-489e-9e9f-489eb4afea08)

**Comment by juacas** [comment]
Hi @adnbes, thank you for reporting.

I've seen that the <noscript> message is shown while previewing, only.
I'll check for a proper way of notifying.

**Comment by juacas** [comment]
It should be fixed in v1.5.2
Thank you again.
