### ISSUE TITLE
Table name quizaccess_delayedattempt

### ISSUE THREAD

**Issue by mudrd8mz** [juacas/quizaccess_activatedelayedattempt#4]
The plugin creates a new table quizaccess_delayedattempt - but such a table would be implicitly "owned" by a plugin called "quizaccess_delayedattempt" which does not match the component name of your plugin. Is there a reason for not having the plugin name in synch with the DB table name prefix?

**Comment by juacas** [comment]
It's because the maximum length of the table names. It should be shorter than 28 chars, if memory serves.

**Comment by mudrd8mz** [comment]
Thought so. And did you consider renaming the whole plugin to `quizaccess_delayedattempt` then?

**Comment by juacas** [comment]
Indeed, but it will impact seriously in the productions servers in wich the plugin was installed before the table were implemented... sigh! I'm delaying this until the end of the academic year in the summer.
Is this a stopper?

**Comment by mudrd8mz** [comment]
Well, once the plugin is approved in the plugins directory and spread globally, it will be hard (if not impossible) to rename it later. So better to have these things sorted out since the day zero. Also, if we approve it now as-is, what if someone implements another plugin named `quizaccess_delayedattempt` in the future? There would be a collision and your plugin would be blamed for not following the naming guidelines (and I would be blamed for approving it ;-)).

**Comment by mudrd8mz** [comment]
BTW, if you decide to go and rename the plugin, it might be wise to choose something like `quizaccess_ada` or so - to give yourself enough space for even more table name suffixes.

However, if you decide to keep things as are, that's an option too. I would understand it, even though I still think it would be better to rename it.

**Comment by juacas** [comment]
OK. I agree. I'll try to refactor the plugin ASAP.
I'm going to split the plugin in two branches temporally.

**Comment by mudrd8mz** [comment]
Right. In that case, we will need to delete the currently submitted plugin from the plugins directory. There is no way to rename it there and it will need to be submitted as a new plugin. Please let me know once I can do it (assuming you may want to copy description and screenshots from there).

Many thanks and sorry for this extra work. I believe it is for a good thing.

**Comment by juacas** [comment]
Thank you for your advice.
I've renamed the plugin. It is uploaded at https://moodle.org/plugins/quizaccess_delayed 
Sorry for the inconveniences. I should have thought of that before.

**Comment by juacas** [comment]
By the way, the old submission can be deleted.

**Comment by mudrd8mz** [comment]
Thank you @juacas 

Just noting it may be a good idea to rename this repository at Github too for consistency. Github allows to do that and it also keeps the automatic / transparent redirect for the old URL.

**Comment by juacas** [comment]
I'm researching how to make this change without disturbing current users. I'm not sure how to make that change without having to change the "remotes" of the repositories.
But I'll do it sooner of later.

**Comment by mudrd8mz** [comment]
https://help.github.com/en/github/administering-a-repository/renaming-a-repository

> without having to change the "remotes" of the repositories.

As I said above, the old URL will continue working. GitHub transparently redirects it to the new URL.

**Comment by juacas** [comment]
Thanks, I didn't found that page. 
I'll rename the repository to quizaccess_delayed.

**Comment by juacas** [comment]
Done.
Thanks for your help.
