### ISSUE TITLE
Start attempt button doesn't show up when countdown ends

### ISSUE THREAD

**Issue by izendegi** [juacas/quizaccess_activatedelayedattempt#5]
Hi there,

I've realized that, when I'm in a quiz logged in as a student, I see the countdown and a disabled "Start attempt" button, but when the countdown ends the button disappears instead of been enabled.

The button shows up if the page is reloaded, but I've read in the docs that `The “Activate Delayed Attempt” plugin makes the “Attempt quiz now” button auto-enable at quiz open timing plus a randomized delay, without requiring to refresh the page` so I guess that the button should appear without refreshing the page, isn't it?

This behaviour happens to me on Moodle 3.8 with the latest version of this plugin, using Firefox 76 and Chrome 81.

Thanks in advance!

**Comment by juacas** [comment]
Thank you for your report. 
There was an error with the DIV indentation. The fix is on branch "**master_longname**".
This new branch contains the plugin with the former name. The plugin will change the name to quizaccess_delayed and the master and develop branches will change the name.

**Comment by izendegi** [comment]
I've tested your fix and it worked like a charm, thank you!

Regarding to the name changing, I've just installed the plugin on a testing enviroment, so I guess I can just uninstall the old plugin and install the new branch once #6 is finished, is that right?

**Comment by juacas** [comment]
You're right. The renamed plugin is already in master and develop.
