### ISSUE TITLE
Invalid link in the description

### ISSUE THREAD

**Issue by mudrd8mz** [juacas/quizaccess_activatedelayedattempt#8]
The description text at https://moodle.org/plugins/quizaccess_delayed starts with

> There is a tutorial page at https://juacas.github.io/quizaccess_activatedelayedattempt/index.html

but that URL does not work. Maybe it is because of the repo rename?

**Comment by mudrd8mz** [comment]
Looks likely because https://juacas.github.io/quizaccess_delayed/index.html works well.

**Comment by mudrd8mz** [comment]
While being there, can you also please update the Bug tracker URL and other fields to point to the new location. Thank you.

**Comment by juacas** [comment]
Updated!
I focused all my attention in the source code and forgot the registry in the Moodle database.
Thank you.
